n_ion_species = 1
n_neutral_species = 1
base_directory = "nothing"
evolve_moments_density = true
evolve_moments_parallel_flow = false
evolve_moments_parallel_pressure = false
evolve_moments_conservation = true
T_e = 1.0
initial_density1 = 0.5
initial_temperature1 = 1.0
initial_density2 = 0.5
initial_temperature2 = 1.0
z_IC_density_amplitude1 = 0.5
z_IC_density_phase1 = 0.0
z_IC_upar_amplitude1 = 0.0
z_IC_upar_phase1 = 0.0
z_IC_temperature_amplitude1 = 0.5
z_IC_temperature_phase1 = 3.141592653589793
z_IC_density_amplitude2 = 0.5
z_IC_density_phase2 = 3.141592653589793
z_IC_upar_amplitude2 = 0.0
z_IC_upar_phase2 = 0.0
z_IC_temperature_amplitude2 = 0.5
z_IC_temperature_phase2 = 0.0
charge_exchange_frequency = 0.6283185307179586
ionization_frequency = 0.0

[z]
ngrid = 81
nelement = 1
bc = "periodic"
discretization = "finite_difference"

[vpa]
ngrid = 241
nelement = 1
L = 8.0
bc = "periodic"
discretization = "finite_difference"

[timestepping]
nstep = 100
dt = 0.0005
nwrite = 200
n_rk_stages = 4
split_operators = false
