run_name = "wall-bc_recyclefraction0.5_split3_v2"
steady_state_residual = true
converged_residual_value = 1.0e-3
#runtime_plots = true
n_ion_species = 1
n_neutral_species = 1
boltzmann_electron_response = true
evolve_moments_density = true
evolve_moments_parallel_flow = true
evolve_moments_parallel_pressure = true
evolve_moments_conservation = true
recycling_fraction = 0.5
krook_collisions = true
T_e = 0.2 # 1.0
T_wall = 0.1
initial_density1 = 1.0
initial_temperature1 = 1.0
z_IC_option1 = "gaussian"
z_IC_density_amplitude1 = 0.001
z_IC_density_phase1 = 0.0
z_IC_upar_amplitude1 = 1.0
z_IC_upar_phase1 = 0.0
z_IC_temperature_amplitude1 = 0.0
z_IC_temperature_phase1 = 0.0
vpa_IC_option1 = "gaussian"
vpa_IC_density_amplitude1 = 1.0
vpa_IC_density_phase1 = 0.0
vpa_IC_upar_amplitude1 = 0.0
vpa_IC_upar_phase1 = 0.0
vpa_IC_temperature_amplitude1 = 0.0
vpa_IC_temperature_phase1 = 0.0
initial_density2 = 1.0
initial_temperature2 = 1.0
z_IC_option2 = "gaussian"
z_IC_density_amplitude2 = 0.001
z_IC_density_phase2 = 0.0
z_IC_upar_amplitude2 = -1.0
z_IC_upar_phase2 = 0.0
z_IC_temperature_amplitude2 = 0.0
z_IC_temperature_phase2 = 0.0
vpa_IC_option2 = "gaussian"
vpa_IC_density_amplitude2 = 1.0
vpa_IC_density_phase2 = 0.0
vpa_IC_upar_amplitude2 = 0.0
vpa_IC_upar_phase2 = 0.0
vpa_IC_temperature_amplitude2 = 0.0
vpa_IC_temperature_phase2 = 0.0
charge_exchange_frequency = 0.75
ionization_frequency = 0.5
constant_ionization_rate = false
#nstep = 50000
nstep = 100000
#dt = 1.0e-4
dt = 2.0e-5
nwrite = 10000
nwrite_dfns = 10000
use_semi_lagrange = false
n_rk_stages = 4
split_operators = false
r_ngrid = 1
r_nelement = 1
z_ngrid = 9
z_nelement = 32
z_nelement_local = 4
z_bc = "wall"
z_discretization = "chebyshev_pseudospectral"
vpa_ngrid = 10
vpa_nelement = 63
vpa_L = 18.0
vpa_bc = "zero"
vpa_discretization = "chebyshev_pseudospectral"
vz_ngrid = 10
vz_nelement = 63
vz_L = 18.0
vz_bc = "zero"
vz_discretization = "chebyshev_pseudospectral"

[ion_source]
active = true
z_profile = "parabolic"
#z_width = 0.125
z_relative_minimum = 0.5
source_strength = 1.0
source_T = 2.0

[numerical_dissipation]
vpa_dissipation_coefficient = 4.0e-1
#vpa_dissipation_coefficient = 1.0e-1
#vpa_dissipation_coefficient = 1.0e-2
#vpa_dissipation_coefficient = 1.0e-3
force_minimum_pdf_value = 0.0
