[deps]
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
MathTeXEngine = "0a4f8689-d25c-4efe-a92b-7142dfc1aa53"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
