n_ion_species = 1
n_neutral_species = 0
electron_physics = "boltzmann_electron_response"
#electron_physics = "boltzmann_electron_response_with_simple_sheath"
evolve_moments_density = false
evolve_moments_parallel_flow = false
evolve_moments_parallel_pressure = false
evolve_moments_conservation = false
force_Er_zero_at_wall = false #true
Er_constant = 0.0
T_e = 1.0
T_wall = 1.0
initial_density1 = 0.5
initial_temperature1 = 1.0
initial_density2 = 0.5
initial_temperature2 = 1.0
z_IC_option1 = "sinusoid"
z_IC_density_amplitude1 = 0.001
z_IC_density_phase1 = 0.0
z_IC_upar_amplitude1 = 0.0
z_IC_upar_phase1 = 0.0
z_IC_temperature_amplitude1 = 0.0
z_IC_temperature_phase1 = 0.0
z_IC_option2 = "sinusoid"
z_IC_density_amplitude2 = 0.001
z_IC_density_phase2 = 0.0
z_IC_upar_amplitude2 = 0.0
z_IC_upar_phase2 = 0.0
z_IC_temperature_amplitude2 = 0.0
z_IC_temperature_phase2 = 0.0
charge_exchange_frequency = 0.0
ionization_frequency = 0.0
z_ngrid = 5
z_nelement = 32
z_nelement_local = 32
z_bc = "wall"
z_discretization = "chebyshev_pseudospectral"
r_ngrid = 5
r_nelement = 32
r_nelement_local = 32
r_bc = "periodic"
r_discretization = "chebyshev_pseudospectral"
vpa_ngrid = 5
vpa_nelement = 32
vpa_L = 12.0
vpa_bc = "zero"
vpa_discretization = "chebyshev_pseudospectral"
vperp_ngrid = 5
vperp_nelement = 16
vperp_L = 6.0
#vperp_discretization = "finite_difference"
#vperp_discretization = "chebyshev_pseudospectral"
vperp_discretization = "gausslegendre_pseudospectral"
vperp_bc = "zero"

vz_ngrid = 17
vz_nelement = 4
vz_L = 12.0
vz_bc = "periodic"
vz_discretization = "chebyshev_pseudospectral"

vr_ngrid = 17
vr_nelement = 4
vr_L = 12.0
vr_bc = "periodic"
vr_discretization = "chebyshev_pseudospectral"

vzeta_ngrid = 17
vzeta_nelement = 4
vzeta_L = 12.0
vzeta_bc = "periodic"
vzeta_discretization = "chebyshev_pseudospectral"

[timestepping]
nstep = 2000
dt = 0.0005
nwrite = 200
nwrite_dfns = 200
split_operators = false

[manufactured_solns]
 use_for_advance=true
 use_for_init=true
 # constant to be used to control Ez divergence in MMS tests
 epsilon_offset=0.1
 # bool to control if dfni is a function of vpa or vpabar in MMS test
 use_vpabar_in_mms_dfni=true
 alpha_switch=1.0
 type="default"
[ion_numerical_dissipation]
vpa_dissipation_coefficient = 0.001
vperp_dissipation_coefficient = 0.001
#z_dissipation_coefficient = 0.1
r_dissipation_coefficient = 0.01

[geometry]
option="1D-mirror"
DeltaB=0.5
#option="constant-helical"
pitch=0.5
rhostar = 1.0
