[reactions]
charge_exchange_frequency = 0.888576587620418
ionization_frequency = 0.0

[evolve_moments]
density = true
parallel_flow = true
pressure = false

[r]
ngrid = 1
nelement = 1

[z]
ngrid = 9
nelement = 2
bc = "periodic"
discretization = "chebyshev_pseudospectral"

[vpa]
ngrid = 17
nelement = 8
L = 11.313708498984761
bc = "periodic"
discretization = "chebyshev_pseudospectral"

[vz]
ngrid = 17
nelement = 8
L = 11.313708498984761
bc = "periodic"
discretization = "chebyshev_pseudospectral"

[composition]
n_ion_species = 1
n_neutral_species = 1
electron_physics = "boltzmann_electron_response"
T_e = 1.0

[ion_species_1]
initial_density = 0.5
initial_temperature = 0.3333333333333333

[neutral_species_1]
initial_density = 0.5
initial_temperature = 0.3333333333333333

[z_IC_ion_species_1]
initialization_option = "sinusoid"
density_amplitude = 0.001
density_phase = 0.0
upar_amplitude = 0.0
upar_phase = 0.0
temperature_amplitude = 0.0
temperature_phase = 0.0

[z_IC_neutral_species_1]
initialization_option = "sinusoid"
density_amplitude = 0.001
density_phase = 0.0
upar_amplitude = 0.0
upar_phase = 0.0
temperature_amplitude = 0.0
temperature_phase = 0.0

[timestepping]
nstep = 1500
dt = 0.001414213562373095
nwrite = 20
split_operators = false
