n_ion_species = 1
n_neutral_species = 1
#boltzmann_electron_response = false
electron_physics = "kinetic_electrons"
evolve_moments_density = false
evolve_moments_parallel_flow = false
evolve_moments_parallel_pressure = false
evolve_moments_conservation = false
T_e = 1.0
T_wall = 1.0
initial_density1 = 1.0
initial_temperature1 = 1.0
z_IC_option1 = "gaussian"
z_IC_density_amplitude1 = 0.001
z_IC_density_phase1 = 0.0
z_IC_upar_amplitude1 = 1.0
z_IC_upar_phase1 = 0.0
z_IC_temperature_amplitude1 = 0.0
z_IC_temperature_phase1 = 0.0
vpa_IC_option1 = "gaussian"
vpa_IC_density_amplitude1 = 1.0
vpa_IC_density_phase1 = 0.0
vpa_IC_upar_amplitude1 = 0.0
vpa_IC_upar_phase1 = 0.0
vpa_IC_temperature_amplitude1 = 0.0
vpa_IC_temperature_phase1 = 0.0
initial_density2 = 1.0
initial_temperature2 = 1.0
z_IC_option2 = "gaussian"
z_IC_density_amplitude2 = 0.001
z_IC_density_phase2 = 0.0
z_IC_upar_amplitude2 = 0.0
z_IC_upar_phase2 = 0.0
z_IC_temperature_amplitude2 = 0.0
z_IC_temperature_phase2 = 0.0
vpa_IC_option2 = "gaussian"
vpa_IC_density_amplitude2 = 1.0
vpa_IC_density_phase2 = 0.0
vpa_IC_upar_amplitude2 = 0.0
vpa_IC_upar_phase2 = 0.0
vpa_IC_temperature_amplitude2 = 0.0
vpa_IC_temperature_phase2 = 0.0
charge_exchange_frequency = 2.0
electron_charge_exchange_frequency = 0.0
nu_ei = 0.0
krook_collisions_option = "reference_parameters"
ionization_frequency = 2.0
electron_ionization_frequency = 2.0
ionization_energy = 1.0
constant_ionization_rate = false
r_ngrid = 1
r_nelement = 1
z_ngrid = 5
#z_nelement = 32
z_nelement = 64
#z_nelement = 128
z_bc = "wall"
z_discretization = "chebyshev_pseudospectral"
z_spacing_option = "sqrt"
vpa_ngrid = 5
#vpa_nelement = 40
vpa_nelement = 80
vpa_L = 12.0 #8.0
vpa_bc = "zero"
vpa_discretization = "chebyshev_pseudospectral"
#vpa_discretization = "gausslegendre_pseudospectral"
vz_ngrid = 17
vz_nelement = 10
vz_L = 8.0
vz_bc = "zero"
vz_discretization = "chebyshev_pseudospectral"

[output]
ascii_output = true

[electron_numerical_dissipation]
#moment_dissipation_coefficient = 0.0001
#moment_dissipation_coefficient = 1.0
#vpa_dissipation_coefficient = 0.002
#vpa_dissipation_coefficient = 0.2
#vpa_dissipation_coefficient = 2.0
vpa_dissipation_coefficient = 20.0

[timestepping]
nstep = 40000
#nstep = 1
dt = 0.0005
nwrite = 200
