[reactions]
charge_exchange_frequency = 0.888576587620418
ionization_frequency = 0.0

[evolve_moments]
density = true
parallel_flow = true
pressure = true

[r]
ngrid = 1
nelement = 1

[z]
ngrid = 100
nelement = 1
bc = "periodic"
discretization = "finite_difference"

[vpa]
ngrid = 400
nelement = 1
L = 13.856406460551018
bc = "periodic"
discretization = "finite_difference"

[vz]
ngrid = 400
nelement = 1
L = 13.856406460551018
bc = "periodic"
discretization = "finite_difference"

[composition]
n_ion_species = 1
n_neutral_species = 1
electron_physics = "boltzmann_electron_response"
T_e = 1.0
T_wall = 1.0

[ion_species_1]
initial_density = 0.5
initial_temperature = 0.3333333333333333

[z_IC_ion_species_1]
initialization_option = "sinusoid"
density_amplitude = 0.5
density_phase = 0.0
upar_amplitude = 0.0
upar_phase = 0.0
temperature_amplitude = 0.5
temperature_phase = 3.14159265359

[neutral_species_1]
initial_density = 0.5
initial_temperature = 0.3333333333333333

[z_IC_neutral_species_1]
initialization_option = "sinusoid"
density_amplitude = 0.5
density_phase = 3.14159265359
upar_amplitude = 0.0
upar_phase = 0.0
temperature_amplitude = 0.5
temperature_phase = 0.0

[timestepping]
nstep = 200
dt = 0.0007071067811865475
nwrite = 20
split_operators = false
