combine_outer = ["charge_exchange_frequency"]

[composition]
n_ion_species = 1
n_neutral_species = 1
boltzmann_electron_response = true
T_e = 1.0

[z_IC_ion_species_1]
initial_density = [1.0e-5, 0.5, 1.0, 1.5, 1.99999]
initial_temperature = 1.0
initialization_option = "sinusoid"
density_amplitude = 0.001
density_phase = 0.0
upar_amplitude = 0.0
upar_phase = 0.0
temperature_amplitude = 0.0
temperature_phase = 0.0

[z_IC_neutral_species_1]
initial_density = [1.99999, 1.5, 1.0, 0.5, 1.0e-5]
initial_temperature = 1.0
initialization_option = "sinusoid"
density_amplitude = 0.001
density_phase = 0.0
upar_amplitude = 0.0
upar_phase = 0.0
temperature_amplitude = 0.0
temperature_phase = 0.0

[reactions]
charge_exchange_frequency = [0.0, 0.2, 0.4, 0.6, 0.8, 1.0, 1.2, 1.4, 1.6, 1.8, 2.0, 2.2, 2.4, 2.6, 2.8, 3.0, 3.2, 3.4, 3.6, 3.8, 4.0, 4.2, 4.4, 4.6, 4.8, 5.0, 5.2, 5.4, 5.6, 5.8, 6.0, 6.2]
ionization_frequency = 0.0

[evolve_moments]
density = true
parallel_flow = true
parallel_pressure = false
moments_conservation = true

[r]
ngrid = 1
nelement = 1

[z]
ngrid = 17
nelement = 2
bc = "periodic"
discretization = "chebyshev_pseudospectral"

[vpa]
pa_ngrid = 17
pa_nelement = 8
pa_L = 8.0
pa_bc = "periodic"
pa_discretization = "chebyshev_pseudospectral"

[vz]
ngrid = 17
nelement = 8
L = 8.0
bc = "periodic"
discretization = "chebyshev_pseudospectral"

[timestepping]
nstep = 2500
dt = 2.0e-3
nwrite = 20
split_operators = false
